Nombre1Accionista=input("Ingrese el nombre del primer accionista: ")
Cap1A=float(input("Ingrese el monto total del dinero invertido: "))
Nombre2Accionista=input("Ingrese el nombre del segundo accionista: ")
Cap2A=float(input("Ingrese el monto total del dinero invertido: "))
Nombre3Accionista=input("Ingrese el nombre del tercer accionista: ")
Cap3A=float(input("Ingrese el monto total del dinero invertido: "))
print("El porcentaje de capital invertido por",Nombre1Accionista,"es el",int(Cap1A*100/(Cap1A+Cap2A+Cap3A)),"%.")
print("El porcentaje de capital invertido por",Nombre2Accionista,"es el",int(Cap2A*100/(Cap1A+Cap2A+Cap3A)),"%.")
print("El porcentaje de capital invertido por",Nombre3Accionista,"es el",int(Cap3A*100/(Cap1A+Cap2A+Cap3A)),"%.")

