numero1=int(input("Ingrese un numero entero: "))
numero2=int(input("Ingrese otro numero entero: "))
numero3=int(input("Ingreso un tercer numero entero: "))
print("La suma de los tres numeros ingresados es: ",numero1+numero2+numero3)
print("El promedio de los tres numeros es: ",(numero1+numero2+numero3)/3)
